name: build & tests

on:
  push:
    branches: 
      - 'master'
      
  pull_request:
    branches: 
      - 'master'

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    # Set up .NET SDK  
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore --configuration Release
      
    - name: Test
      run: dotnet test --no-build --no-restore --configuration Release --verbosity normal
